import { useEffect, useMemo, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { Scale, Plus, Search, FileText, MessageSquareText, Sun, Moon, ChevronDown, ArrowUp, Paperclip, Mic, Sparkles, ShieldCheck, Clock3, BookOpen, PanelLeftClose, Trash2, Download, Activity, MoreHorizontal, Pin, Pencil, FileDown, Network, LoaderCircle, X } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { askQuestion, searchCases, analyzeDocument, checkHealth } from "./api";
import { setMode,setTheme,setQuery,setBusy,setError,setAnswer,setSearchResults,setDocumentResult,setIncludeCitations,newSession,selectSession,clearSession,addMessage,deleteSession,renameSession,togglePin } from "./store";

const starterPrompts = [{title:"Understand a legal provision",detail:"Explain a section in plain language",query:"Explain the legal elements and practical meaning of Section 302 IPC."},{title:"Compare case law",detail:"Find relevant judgments and distinctions",query:"Find relevant Supreme Court judgments on anticipatory bail."},{title:"Review a document",detail:"Extract issues and supporting provisions",mode:"document",query:"Summarize this document and identify the key legal issues."}];
const short = (value,n=220) => value && value.length>n ? value.slice(0,n).trim()+"…" : value || "";
function App(){
 const dispatch=useDispatch(); const state=useSelector(s=>s.workspace); const [health,setHealth]=useState(false); const [file,setFile]=useState(null); const [sidebar,setSidebar]=useState(true); const [listening,setListening]=useState(false); const [menuId,setMenuId]=useState(null);
 useEffect(()=>{document.documentElement.classList.toggle("dark",state.theme==="dark");},[state.theme]);
 useEffect(()=>{checkHealth().then(()=>setHealth(true)).catch(()=>setHealth(false));const id=setInterval(()=>checkHealth().then(()=>setHealth(true)).catch(()=>setHealth(false)),45000);return()=>clearInterval(id);},[]);
 const results=state.searchResults||[];
 const chartData=useMemo(()=>results.slice(0,10).map((r,i)=>({name:"Source "+(i+1),score:Number(r.score||0),label:r.doc_id||r.chunk_id||("Source "+(i+1))})),[results]);
 async function submit(value=state.query){const query=value.trim();if(!query||state.busy)return;dispatch(setQuery(query));dispatch(setError(""));dispatch(setBusy(true));dispatch(addMessage({role:"user",query,text:query,at:new Date().toISOString()}));try{if(state.mode==="search"){const data=await searchCases(query);dispatch(setSearchResults(data.results||[]));}else if(state.mode==="document"){if(!file)throw new Error("Choose a PDF document before running document analysis.");const data=await analyzeDocument(file,query);dispatch(setDocumentResult(data));}else{const data=await askQuestion(query);dispatch(setAnswer(data));}dispatch(addMessage({role:"assistant",query,text:"Research completed",at:new Date().toISOString()}));}catch(e){dispatch(setError(e.message||"Something went wrong."));}finally{dispatch(setBusy(false));}}
 function startVoice(){const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition){dispatch(setError("Voice input is not supported in this browser. Try Chrome or Edge."));return;}const recognition=new Recognition();recognition.lang="en-IN";recognition.interimResults=false;recognition.onstart=()=>setListening(true);recognition.onend=()=>setListening(false);recognition.onerror=()=>{setListening(false);dispatch(setError("Voice input could not start. Check microphone permission."));};recognition.onresult=e=>dispatch(setQuery((state.query+" "+e.results[0][0].transcript).trim()));recognition.start();}
 function changeMode(mode){dispatch(setMode(mode));dispatch(setError(""));dispatch(setQuery(""));}
 function exportSession(id=state.activeId){const session=state.sessions.find(s=>s.id===id);const text=(session?.messages||[]).map(m=>(m.role==="user"?"YOU":"LEXASSIST")+": "+(m.text||m.query||"")).join("\n\n");const url=URL.createObjectURL(new Blob([text||"No messages yet."],{type:"text/plain"}));const a=document.createElement("a");a.href=url;a.download=(session?.title||"lexassist-session").replace(/[^a-z0-9-_]+/gi,"-")+".txt";a.click();URL.revokeObjectURL(url);setMenuId(null);}
function renameCurrent(s){const title=window.prompt("Rename research session",s.title);if(title?.trim())dispatch(renameSession({id:s.id,title}));setMenuId(null);}
 return <div className="app-shell">
 {sidebar&&<aside className="sidebar"><div className="brand"><div className="brand-mark"><Scale size={21}/></div><div><div className="brand-name">LexAssist<span> AI</span></div><div className="brand-caption">LEGAL INTELLIGENCE</div></div><button className="icon-btn sidebar-close" onClick={()=>setSidebar(false)} aria-label="Collapse sidebar"><PanelLeftClose size={17}/></button></div>
 <button className="new-session" onClick={()=>dispatch(newSession())}><Plus size={17}/> New research session <span>⌘ K</span></button>
 <div className="nav-label">WORKSPACES</div><nav className="nav-list"><button className={state.mode==="qa"?"nav-item active":"nav-item"} onClick={()=>changeMode("qa")}><MessageSquareText size={17}/> Legal Research <span className="nav-count">01</span></button><button className={state.mode==="search"?"nav-item active":"nav-item"} onClick={()=>changeMode("search")}><Search size={17}/> Case Law Search</button><button className={state.mode==="document"?"nav-item active":"nav-item"} onClick={()=>changeMode("document")}><FileText size={17}/> Document Analysis</button></nav>
 <div className="nav-label recent-label">RECENT RESEARCH <button title="Export current session" onClick={exportSession}><Download size={14}/></button></div><div className="session-list">{state.sessions.slice().sort((a,b)=>Number(Boolean(b.pinned))-Number(Boolean(a.pinned))).slice(0,12).map(s=><div className={"session-row "+(s.id===state.activeId?"session-active":"")} key={s.id}><button className="session-select" onClick={()=>dispatch(selectSession(s.id))}><MessageSquareText size={15}/>{s.pinned&&<Pin size={12} className="pinned-icon"/>}<span>{s.title}</span></button><button className="session-menu-trigger" title="Session options" aria-label={"Options for "+s.title} onClick={e=>{e.stopPropagation();setMenuId(menuId===s.id?null:s.id)}}><MoreHorizontal size={16}/></button>{menuId===s.id&&<div className="session-menu"><button onClick={()=>renameCurrent(s)}><Pencil size={14}/> Rename</button><button onClick={()=>{exportSession(s.id)}}><Download size={14}/> Export</button><button onClick={()=>{dispatch(togglePin(s.id));setMenuId(null)}}><Pin size={14}/> {s.pinned?"Unpin":"Pin"}</button><button className="menu-danger" onClick={()=>{dispatch(deleteSession(s.id));setMenuId(null)}}><Trash2 size={14}/> Delete</button></div>}</div>)}</div>
 <div className="sidebar-bottom"><div className="plan-card"><div className="plan-icon"><ShieldCheck size={17}/></div><div><b>Evidence-first research</b><p>Answers grounded in retrieved sources.</p></div></div><div className="profile"><div className="profile-avatar">LR</div><div className="profile-copy"><b>Legal Researcher</b><span>Personal workspace</span></div><button className="icon-btn" onClick={()=>dispatch(setTheme(state.theme==="dark"?"light":"dark"))} aria-label="Toggle theme">{state.theme==="dark"?<Sun size={17}/>:<Moon size={17}/>}</button></div></div></aside>}
 <main className="main-panel"><header className="topbar">{!sidebar&&<button className="icon-btn" onClick={()=>setSidebar(true)}><PanelLeftClose size={18}/></button>}<div className="breadcrumbs"><span>Workspace</span><span className="crumb-slash">/</span><b>{state.mode==="qa"?"Legal Research":state.mode==="search"?"Case Law Search":"Document Analysis"}</b></div><div className="topbar-right"><div className="status"><span className={health?"status-dot":"status-dot offline"}></span>{health?"API connected":"API unavailable"}</div><button className="icon-btn" title="Toggle theme" onClick={()=>dispatch(setTheme(state.theme==="dark"?"light":"dark"))}>{state.theme==="dark"?<Sun size={17}/>:<Moon size={17}/>}</button><button className="export-btn" onClick={exportSession}><Download size={15}/> Export</button></div></header>
 <div className="workspace-content"><div className="page-heading"><div><div className="eyebrow"><Sparkles size={13}/> LEGAL RESEARCH WORKSPACE</div><h1>{state.mode==="qa"?"Research with confidence.":state.mode==="search"?"Find the authorities that matter.":"Understand every document."}</h1><p>{state.mode==="qa"?"Ask a legal question and get a structured answer backed by retrieved evidence.":state.mode==="search"?"Search indexed legal materials and inspect relevant passages, ranked by retrieval.":"Upload a PDF to extract its text and identify the legal issues that deserve attention."}</p></div><div className="heading-mark"><Scale size={27}/><span>INDIA</span></div></div>
 <div className="mode-tabs"><button className={state.mode==="qa"?"mode-tab selected": "mode-tab"} onClick={()=>changeMode("qa")}><MessageSquareText size={16}/> Ask legal AI</button><button className={state.mode==="search"?"mode-tab selected":"mode-tab"} onClick={()=>changeMode("search")}><Search size={16}/> Search cases</button><button className={state.mode==="document"?"mode-tab selected":"mode-tab"} onClick={()=>changeMode("document")}><FileText size={16}/> Analyze PDF</button><div className="tabs-spacer"/><label className="citation-toggle"><input type="checkbox" checked={state.includeCitations} onChange={e=>dispatch(setIncludeCitations(e.target.checked))}/> Include citations</label></div>
 {state.mode==="document"&&<div className="upload-card"><div className="upload-icon"><FileText size={20}/></div><div className="upload-copy"><b>{file?file.name:"Add a PDF document"}</b><span>{file?(Math.max(1,Math.round(file.size/1024))+" KB · Ready to analyze"):"PDF only · up to 15 MB"}</span></div><label className="upload-button">Choose file<input type="file" accept="application/pdf,.pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/></label>{file&&<button className="icon-btn" onClick={()=>setFile(null)} aria-label="Remove PDF"><X size={16}/></button>}</div>}
 {state.mode==="qa"&&!state.answer&&!state.busy&&<section className="welcome-grid"><div className="welcome-copy"><div className="welcome-pill"><span className="welcome-dot"/> GROUNDED LEGAL ASSISTANCE</div><h2>Good research starts<br/>with the right question.</h2><p>Explore legal provisions, compare authorities, and build a clearer picture of the law with source-aware AI assistance.</p><div className="welcome-stats"><div><b>01</b><span>Ask a question</span></div><div><b>02</b><span>Retrieve evidence</span></div><div><b>03</b><span>Review the answer</span></div></div></div><div className="welcome-art"><div className="art-orbit orbit-one"></div><div className="art-orbit orbit-two"></div><div className="art-document"><div className="art-doc-head"><Scale size={19}/><span>LEGAL BRIEF</span></div><div className="art-line line-long"></div><div className="art-line"></div><div className="art-line line-short"></div><div className="art-highlight"></div><div className="art-line"></div><div className="art-line line-long"></div><div className="art-stamp"><ShieldCheck size={17}/> SOURCE CHECKED</div></div><div className="floating-chip chip-top"><BookOpen size={15}/> Case law</div><div className="floating-chip chip-bottom"><Activity size={15}/> Hybrid retrieval</div></div></section>}
 {state.mode==="qa"&&!state.answer&&!state.busy&&<div className="suggestion-grid">{starterPrompts.map((p,i)=><button className="suggestion-card" key={p.title} onClick={()=>{if(p.mode)changeMode(p.mode);dispatch(setQuery(p.query));}}><span className={"suggestion-icon si-"+i}>{i===0?<BookOpen size={17}/>:i===1?<Network size={17}/>:<FileText size={17}/>}</span><span className="suggestion-text"><b>{p.title}</b><small>{p.detail}</small></span><ArrowUp className="suggestion-arrow" size={15}/></button>)}</div>}
 {state.error&&<div className="error-banner"><X size={16}/><span>{state.error}</span><button onClick={()=>dispatch(setError(""))}>Dismiss</button></div>}
 {state.busy&&<div className="loading-card"><LoaderCircle className="spin" size={20}/><div><b>{state.mode==="search"?"Searching indexed authorities…":state.mode==="document"?"Analyzing uploaded document…":"Retrieving evidence and drafting an answer…"}</b><span>This can take a little while on a cold start.</span></div></div>}
 {state.answer&&<section className="result-card"><div className="result-header"><div className="result-heading"><span className="result-icon"><Sparkles size={17}/></span><div><b>Research answer</b><span>{state.answer.model||"Groq"} · Evidence-grounded response</span></div></div><button className="icon-btn" title="Clear result" onClick={()=>dispatch(clearSession())}><X size={16}/></button></div><div className="answer-body">{state.answer.answer}</div>{state.includeCitations&&state.answer.citations?.length>0&&<div className="citation-area"><div className="section-label">CITATIONS</div><div className="citation-list">{state.answer.citations.map((c,i)=><span className="citation-chip" key={c+i}><BookOpen size={13}/>{c}</span>)}</div></div>}{state.answer.retrieved_chunks?.length>0&&<div className="sources-area"><div className="section-label">RETRIEVED EVIDENCE <span>{state.answer.retrieved_chunks.length} passages</span></div>{state.answer.retrieved_chunks.slice(0,5).map((c,i)=><article className="source-row" key={c.chunk_id||i}><div className="source-index">{String(i+1).padStart(2,"0")}</div><div className="source-content"><b>{c.doc_id||c.chunk_id||"Retrieved passage"}</b><p>{short(c.text,280)}</p></div></article>)}</div>}</section>}
 {state.documentResult&&<section className="result-card"><div className="result-header"><div className="result-heading"><span className="result-icon"><FileText size={17}/></span><div><b>Document analysis</b><span>{state.documentResult.model||"Groq"} · Uploaded PDF</span></div></div></div><div className="answer-body">{state.documentResult.answer}</div>{state.includeCitations&&state.documentResult.citations?.map((c,i)=><span className="citation-chip" key={c+i}>{c}</span>)}{state.documentResult.retrieved_chunks?.length>0&&<div className="sources-area"><div className="section-label">SUPPORTING PASSAGES</div>{state.documentResult.retrieved_chunks.map((c,i)=><article className="source-row" key={i}><div className="source-index">{i+1}</div><div className="source-content"><p>{short(c.text,260)}</p></div></article>)}</div>}</section>}
 {results.length>0&&<section className="result-card"><div className="result-header"><div className="result-heading"><span className="result-icon"><Search size={17}/></span><div><b>Case law search results</b><span>{results.length} retrieved passages · sorted by hybrid rank</span></div></div></div><div className="chart-heading"><div><b>Retrieval score distribution</b><p>Higher scores indicate stronger relative ranking in this result set.</p></div><span className="chart-tag">TOP {chartData.length}</span></div><div className="chart-wrap"><ResponsiveContainer width="100%" height={210}><AreaChart data={chartData} margin={{top:8,right:12,left:2,bottom:0}}><defs><linearGradient id="scoreFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#5268e8" stopOpacity={0.28}/><stop offset="95%" stopColor="#5268e8" stopOpacity={0.02}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="var(--chart-grid)"/><XAxis dataKey="name" tick={{fontSize:11,fill:"var(--muted)"}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:11,fill:"var(--muted)"}} axisLine={false} tickLine={false} width={52}/><Tooltip contentStyle={{background:"var(--panel)",border:"1px solid var(--border)",borderRadius:12,color:"var(--text)"}} formatter={(v)=>[Number(v).toFixed(5),"RRF score"]} labelFormatter={(l,i)=>chartData[i]?.label||l}/><Area type="monotone" dataKey="score" stroke="#5268e8" strokeWidth={2.5} fill="url(#scoreFill)" activeDot={{r:5}}/></AreaChart></ResponsiveContainer></div><div className="search-result-list">{results.map((r,i)=><article className="search-result" key={r.chunk_id||i}><div className="source-index">{String(i+1).padStart(2,"0")}</div><div className="source-content"><div className="search-result-title"><b>{r.doc_id||r.chunk_id||"Legal passage"}</b><span className="score-badge">Score {Number(r.score||0).toFixed(5)}</span></div><p>{r.text||r.content||""}</p>{r.metadata&&<div className="metadata-row">{Object.entries(r.metadata).slice(0,3).map(([k,v])=><span key={k}>{k.replaceAll("_"," ")}: {String(v)}</span>)}</div>}</div></article>)}</div></section>}
 <div className="composer-zone"><div className="composer"><div className="composer-top">{state.mode==="document"?"Ask something about the uploaded PDF":state.mode==="search"?"Search case law, sections, or legal principles":"Ask a legal question"}</div><textarea value={state.query} onChange={e=>dispatch(setQuery(e.target.value))} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();submit();}}} placeholder={state.mode==="search"?"e.g. Supreme Court judgments on anticipatory bail…":state.mode==="document"?"e.g. Identify the key issues and relevant provisions…":"e.g. What are the essential elements of a valid contract?"} rows={2}/><div className="composer-bottom"><div className="composer-tools"><button className={"tool-btn "+(listening?"listening":"")} onClick={startVoice} title="Voice input"><Mic size={16}/><span>{listening?"Listening…":"Voice"}</span></button><span className="composer-note"><ShieldCheck size={13}/> Verify important legal authorities independently</span></div><button className="send-btn" onClick={()=>submit()} disabled={state.busy||!state.query.trim()}>{state.busy?<LoaderCircle className="spin" size={17}/>:<ArrowUp size={17}/>}<span>{state.mode==="search"?"Search":state.mode==="document"?"Analyze":"Ask LexAssist"}</span></button></div></div><div className="composer-foot"><span><span className="keyboard-key">↵</span> to submit <span className="keyboard-key">⇧ ↵</span> for a new line</span><span>AI can make mistakes. Check primary sources.</span></div></div>
 </div></main></div>;
}
export default App;
